executor/JobConsole: make sure client_sock is set before using it
Fixes a crash I observed:

  File "/usr/lib/python3.10/site-packages/valve_gfx_ci/executor/server/executor.py", line 280, in run
    elif fd == self.client_sock.fileno():
  AttributeError: 'NoneType' object has no attribute 'fileno'