config: Look up static templates relative to module.
Next issue using the virtual testing was,

    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/valve_gfx_ci/executor/server/mars.py", line 404, in run
        self.sync_machines()
      File "/usr/local/lib/python3.9/site-packages/valve_gfx_ci/executor/server/mars.py", line 360, in sync_machines
        gitlab.generate_runner_config(self.mars_db)
      File "/usr/local/lib/python3.9/site-packages/valve_gfx_ci/executor/server/gitlab.py", line 44, in generate_runner_config
        with open(config.GITLAB_CONF_TEMPLATE_FILE) as f:
    FileNotFoundError: [Errno 2] No such file or directory:
    '/app/templates/gitlab_runner_config.toml.j2'

We no longer install the templates in the /app directory. We have two
options,

 1. Add a helper to look up the templates relative to the config
 module
 2. Symlink the template directories back into /app, as before.

2. feels more like a hack to me, so 1. has been chosen to fix this issue.

Also remove the environment hardcodings to /app/job_templates, since
they no longer exist!