valvetraces: limit the chunk size for request downloads
Due to https://bugs.python.org/issue42853.

Avoid:

"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/builds/tanty/mesa/install/valve/traces-runner.py", line 291, in run_task
    result = task.run()
  File "/builds/tanty/mesa/install/valve/traces-runner.py", line 245, in run
    self._ensure_trace()
  File "/builds/tanty/mesa/install/valve/traces-runner.py", line 157, in _ensure_trace
    trace = self.client.download_trace(self.trace.filename,
  File "/usr/local/lib/python3.9/dist-packages/valvetraces/__init__.py", line 216, in download_trace
    for chunk in r.iter_content(None):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 515, in read
    data = self._fp.read() if not fp_closed else b""
  File "/usr/lib/python3.9/http/client.py", line 471, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.9/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
OverflowError: signed integer is greater than maximum
"""

Signed-off-by: Andres Gomez <agomez@igalia.com>