gitlab_runner: Do not fail to start if the configuration file was removed
This was a regression from the recent port, if the file is removed at
runtime and you restart the service,

ERROR: Failed to load config stat /etc/gitlab-runner/config.toml: no
such file or directory  builds=0

Instead, simply write out the default in this case.