client: display the help message when no commands are used
If the user were not to use the "run" command, the client would throw
the following exception:

    AttributeError: 'Namespace' object has no attribute 'func'

To fix this, we simply catch the exception, and display the help text.

Fixes: 4636b3d (client: move argument parsing to argsparse's subparsers)